"""add_tenant_id_create_ts_index_to_fileinfo

Revision ID: 2fca35bd0263
Revises: cd1ff38ada1c
Create Date: 2026-07-10 00:08:30.706945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2fca35bd0263'
down_revision: Union[str, Sequence[str], None] = 'cd1ff38ada1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileinfo', schema=None) as batch_op:
        batch_op.create_index('idx_fileinfo_tenant_create', ['tenant_id', 'create_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileinfo', schema=None) as batch_op:
        batch_op.drop_index('idx_fileinfo_tenant_create')

    # ### end Alembic commands ###
