"""sync_models

Revision ID: 3536a5f7d10a
Revises: dc974f248ddf
Create Date: 2026-07-20 20:17:14.424618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3536a5f7d10a'
down_revision: Union[str, Sequence[str], None] = 'dc974f248ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_type', sa.Enum('USER', 'AGENT', 'SYSTEM', name='chatmessagesendertype'), nullable=False),
    sa.Column('event_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_ts_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index('idx_chatmessage_session_create', ['chat_session_id', 'create_ts_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_thread_id'), ['thread_id'], unique=False)

    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=10240), nullable=False),
    sa.Column('status', sa.Enum('INVALID', 'ACTIVE', 'CLOSED', name='chatsessionstatus'), nullable=False),
    sa.Column('create_ts', sa.Integer(), nullable=False),
    sa.Column('update_ts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.create_index('idx_chatsession_user_create', ['user_id', 'create_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_session_chat_session_id'), ['chat_session_id'], unique=True)

    op.create_table('chat_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ARCHIVED', 'ACTIVE', name='chatthreadstatus'), nullable=False),
    sa.Column('create_ts', sa.Integer(), nullable=False),
    sa.Column('update_ts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_thread', schema=None) as batch_op:
        batch_op.create_index('idx_chatthread_session_create', ['chat_session_id', 'create_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_thread_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_thread_thread_id'), ['thread_id'], unique=True)

    op.create_table('thread_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_ts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thread_run', schema=None) as batch_op:
        batch_op.create_index('idx_threadrun_thread_create', ['thread_id', 'create_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_run_run_id'), ['run_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_run_run_id'))
        batch_op.drop_index('idx_threadrun_thread_create')

    op.drop_table('thread_run')
    with op.batch_alter_table('chat_thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_thread_thread_id'))
        batch_op.drop_index(batch_op.f('ix_chat_thread_tenant_id'))
        batch_op.drop_index('idx_chatthread_session_create')

    op.drop_table('chat_thread')
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_chat_session_id'))
        batch_op.drop_index('idx_chatsession_user_create')

    op.drop_table('chat_session')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_thread_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_run_id'))
        batch_op.drop_index('idx_chatmessage_session_create')

    op.drop_table('chat_message')
    # ### end Alembic commands ###
