"""empty message

Revision ID: 54612f083447
Revises: d7607b167a53
Create Date: 2026-07-08 20:24:12.088562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54612f083447'
down_revision: Union[str, Sequence[str], None] = 'd7607b167a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessioninfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('ADMIN', 'USER', 'TENANT_ADMIN', name='usertype'),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_user_user_id', ['user_id'])


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_user_id', type_='unique')

        batch_op.alter_column('user_type',
               existing_type=sa.Enum('ADMIN', 'USER', 'TENANT_ADMIN', name='usertype'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('sessioninfo', schema=None) as batch_op:
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
