"""create_fileinfo_table

Revision ID: 70ba3163a249
Revises: 54612f083447
Create Date: 2026-07-09 02:20:01.764400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70ba3163a249'
down_revision: Union[str, Sequence[str], None] = '54612f083447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileinfo',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('owner_email', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('file_storage_location', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('file_storage_type', sa.Enum('LOCAL', 'S3', name='filestoragetype'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('create_ts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVALID', name='filestatus'), nullable=False),
    sa.Column('vector_db_sync_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='filesyncstatus'), nullable=False),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fileinfo')
    # ### end Alembic commands ###
