"""add_file_md5_hash_to_fileinfo

Revision ID: cd1ff38ada1c
Revises: 70ba3163a249
Create Date: 2026-07-09 03:06:05.438105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd1ff38ada1c'
down_revision: Union[str, Sequence[str], None] = '70ba3163a249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_md5_hash', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileinfo', schema=None) as batch_op:
        batch_op.drop_column('file_md5_hash')

    # ### end Alembic commands ###
