"""empty message

Revision ID: d7607b167a53
Revises: 651c2afea356
Create Date: 2026-07-08 18:40:56.785933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7607b167a53'
down_revision: Union[str, Sequence[str], None] = '651c2afea356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessioninfo',
    sa.Column('sessionid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('create_ts', sa.Integer(), nullable=False),
    sa.Column('expire_ts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVALID', name='sessionstatus'), nullable=False),
    sa.PrimaryKeyConstraint('sessionid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessioninfo')
    # ### end Alembic commands ###
