"""update_fileinfo_index

Revision ID: dc974f248ddf
Revises: 2fca35bd0263
Create Date: 2026-07-10 02:37:27.061226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc974f248ddf'
down_revision: Union[str, Sequence[str], None] = '2fca35bd0263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileinfo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fileinfo_tenant_create'))
        batch_op.create_index('idx_fileinfo_tenant_create_file', ['tenant_id', 'create_ts', 'file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileinfo', schema=None) as batch_op:
        batch_op.drop_index('idx_fileinfo_tenant_create_file')
        batch_op.create_index(batch_op.f('idx_fileinfo_tenant_create'), ['tenant_id', 'create_ts'], unique=False)

    # ### end Alembic commands ###
