"""Public schemas shared by the AI Agent and its consumers."""

from shared_common.schemas.ai_agent.enums import (
    AgentCustomStreamEventKind,
    AgentDomainEventKind,
    AgentOutputPartKind,
    AgentProgressStatus,
    AgentRunStatus,
    AgentSourceType,
    AgentReturnReason,
    AgentItemCondition,
)
from shared_common.schemas.ai_agent.custom_stream_events import (
    AgentCustomStreamEventBase,
    AgentProgressStreamEvent,
)
from shared_common.schemas.ai_agent.events import (
    AgentDomainEvent,
    AgentDomainEventBase,
    AgentError,
    AgentOutputProduced,
    AgentProgressReported,
    AgentRunCompleted,
    AgentRunFailed,
    AgentRunInterrupted,
    HumanInputRequested,
    UnixTimestamp,
)
from shared_common.schemas.ai_agent.human_input import (
    AgentResumeCursor,
    HumanInputRequest,
    HumanInputResponse,
)
from shared_common.schemas.ai_agent.human_input_schemas import (
    GetUserByEmailInputModel,
    GetOrdersByEmailInputModel,
    GetOrderDetailsByOrderIdInputModel,
    GetReturnsByOrderIdInputModel,
    GetReturnsByCustomerIdInputModel,
    CreateReturnRequestInputModel,
)
from shared_common.schemas.ai_agent.outputs import (
    AgentOutput,
    AgentOutputPart,
    ECommerceOrderDetailsOutput,
    ECommerceOrderItemOutput,
    ECommerceOrderOutput,
    ECommerceOrdersOutput,
    ECommerceReturnRequestOutput,
    ECommerceReturnsByCustomerOutput,
    ECommerceReturnsByOrderOutput,
    ECommerceUserOutput,
    ECommerceCreateReturnOutput,
    SourceReference,
    SourcesPart,
    StructuredDataPart,
    TextPart,
)
from shared_common.schemas.ai_agent.rag_file_import import RAGFileImportResult
from shared_common.schemas.ai_agent.requests import (
    AgentCreateRunRequest,
    AgentCreateRunResponse,
    AgentGetStateEventsRequest,
    AgentJoinStreamRequest,
    AgentListRunsRequest,
    AgentListRunsResponse,
    AgentRAGFileImportRequest,
    AgentResumeRequest,
    AgentRunObject,
    AgentTurnRequest,
    RAGFileImportPayload,
    UserMessageInput,
)

from shared_common.schemas.ai_agent.schema_ids import (
    AgentOutputSchemaId,
    HumanInputSchemaId,
)

__all__ = [
    "AgentDomainEvent",
    "AgentDomainEventBase",
    "AgentDomainEventKind",
    "AgentCustomStreamEventBase",
    "AgentCustomStreamEventKind",
    "AgentError",
    "AgentOutput",
    "AgentOutputPart",
    "AgentOutputPartKind",
    "AgentOutputSchemaId",
    "AgentOutputProduced",
    "ECommerceOrderDetailsOutput",
    "ECommerceOrderItemOutput",
    "ECommerceOrderOutput",
    "ECommerceOrdersOutput",
    "ECommerceReturnRequestOutput",
    "ECommerceReturnsByCustomerOutput",
    "ECommerceReturnsByOrderOutput",
    "ECommerceUserOutput",
    "ECommerceCreateReturnOutput",
    "AgentCreateRunRequest",
    "AgentCreateRunResponse",
    "AgentGetStateEventsRequest",
    "AgentJoinStreamRequest",
    "AgentListRunsRequest",
    "AgentListRunsResponse",
    "AgentProgressReported",
    "AgentProgressStreamEvent",
    "AgentProgressStatus",
    "AgentRAGFileImportRequest",
    "AgentResumeCursor",
    "AgentResumeRequest",
    "AgentRunCompleted",
    "AgentRunFailed",
    "AgentRunInterrupted",
    "AgentRunObject",
    "AgentRunStatus",
    "AgentSourceType",
    "AgentTurnRequest",
    "HumanInputRequest",
    "HumanInputRequested",
    "HumanInputResponse",
    "HumanInputSchemaId",
    "RAGFileImportPayload",
    "RAGFileImportResult",
    "SourceReference",
    "SourcesPart",
    "StructuredDataPart",
    "TextPart",
    "UnixTimestamp",
    "UserMessageInput",
    "AgentReturnReason",
    "AgentItemCondition",
]

